##############################################################################
################################# makefile ###################################
##############################################################################
#		                                                             #
#   makefile of MCFClass	                                             #
#				                                             #
#   Input:  $(MCFDIR) = the directory where the source is                    #
#									     #
#   Output: $(MCFH)   = the .h files to include				     #
#           $(MCFINC) = the -I$(include directories)			     #
#									     #
#                                VERSION 1.00				     #
#                	        09 - 05 - 2012				     #
#									     #
#			      Antonio Frangioni				     #
#   			   Operations Research Group			     #
#			  Dipartimento di Informatica			     #
#   			     Universita' di Pisa			     #
#									     #
##############################################################################

MCFH = $(MCFDIR)MCFClass.h
MCFINC = -I$(MCFDIR)

############################ End of makefile #################################
