##############################################################################
################################# makefile ###################################
##############################################################################
#                                                                            #
#   makefile of MCFClass                                                     #
#                                                                            #
#   Input:  $(MCFClDIR) = the directory where the source is                  #
#           $(OPTUxH)   = the OPTUtils.h files to include                    #
#           $(OPTUxINC) = the -I$( OPTUtils.h directory )                    #
#                                                                            #
#   Output: $(MCFClH)   = the .h files to include for MCFClass               #
#           $(MCFClINC) = the -I$( include directories for MCFClass )        #
#                                                                            #
#                              Antonio Frangioni                             #
#                          Dipartimento di Informatica                       #
#                              Universita' di Pisa                           #
#                                                                            #
##############################################################################

MCFClH = $(MCFClDIR)MCFClass.h $(OPTUxH)
MCFClINC = -I$(MCFClDIR) $(OPTUxINC)

############################ End of makefile #################################
