The MCFClass Project: OPTtimers Class Reference
OPTtimers Class Reference
Classes in OPTUtils.h
Provides a common interface to the different timing routines that are available in different platforms.
#include <OPTUtils.h>
Public Member Functions
OPTtimers (void)
constructor of the class
void Start (void)
start the timer
void Stop (void)
stop the timer
double Read (void)
Return the elapsed time.
void Read (double &tu, double &ts)
As Read(void) but adds user and system time to tu and ts.
void ReSet (void)
reset the timer
Detailed Description
Provides a common interface to the different timing routines that are available in different platforms.
Member Function Documentation
Read()
double Read (void) inline
Return the elapsed time.
If the clock is ticking, return the total time since the last Start() without stopping the clock; otherwise, return the total elapsed time of all the past runs of the clock since the last ReSet() [see below].
References OPTtimers::Read().
Referenced by OPTtimers::Read(), OPTtimers::Stop(), and MCFClass::TimeMCF().